server:
  port: 8086

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # Don't register with itself
    fetch-registry: false         # Don't fetch registry from itself
    service-url:
      defaultZone: http://localhost:8086/eureka/
